---
- name: Ensure .ssh directory exists for the user
  file:
    path: "/home/{{ target_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Add public SSH key to authorized_keys
  authorized_key:
    user: "{{ target_user }}"
    key: "{{ ssh_public_key_path }}"
    state: present
    exclusive: no