---
- name: Copier le fichier de configuration ssh
  template:
    src: ../templates/sshd_config.txt.j2
    dest: /etc/ssh/sshd_config

- name: Rédémarre ssh
  ansible.builtin.command:
    argv:
      - systemctl
      - restart
      - ssh*

- name: Add iptables rule to set recent list for IPv4
  ansible.builtin.command:
    cmd: iptables -I INPUT -p tcp --dport 22 -m state --state NEW -m recent --set

- name: Add iptables rule to drop excessive SSH attempts for IPv4
  ansible.builtin.command:
    cmd: iptables -I INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 10 --hitcount 10 -j DROP

- name: Add ip6tables rule to set recent list for IPv6
  ansible.builtin.command:
    cmd: ip6tables -I INPUT -p tcp --dport 22 -m state --state NEW -m recent --set

- name: Add ip6tables rule to drop excessive SSH attempts for IPv6
  ansible.builtin.command:
    cmd: ip6tables -I INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 10 --hitcount 10 -j DROP